### ISSUE TITLE
Sorters suddenly disconnect after loading a save.

### ISSUE THREAD

**Issue by cdcrothers** [GreyHak/dsp-belt-reverse#3] opened 2021-06-15 02:36 UTC
![image](https://user-images.githubusercontent.com/16570564/121983688-b825bc00-cd5f-11eb-98ba-dfcc60e4584c.png)

Only mod that I have installed is this one.

Not sure this is a bug with this mod, or simply with the fixVersion for this DSP release.

Game version is 2018.4.12.5889476

Has happened 3 times, so I'm certain at this point that they were previously linked. The container full of wind turbines is proof too, as I only set this assembly line up one time.

**Comment by GreyHak** [comment] 2021-06-15 23:57
Thank you for the report @connorcrothers.  I'm unsure what game version 2018.4.12.5889476 is.  I've tested on the latest mod version 1.1.0 with the latest DSP game version 0.7.18.7103, and I'm unable to reproduce this problem.  My mod doesn't handle the inserters at all.  They're handled automatically by the game.  My mod has code to deal with every other belt interface type.  So if there is an issue, it's in the lack of some support rather than a bug in an existing part of the implementation.  So I would need to be able to reproduce the problem to see what my mod isn't doing.  Is there any chance you'd be able to tell me how to reproduce the issue?

**Comment by cdcrothers** [comment] 2021-06-18 01:16
*0.7.18.7178
> I guess I was looking at the executable's "Product Version"

Noted. Thanks for clarifying. Must have been something else that caused it.

**Comment by muink** [comment] 2021-08-12 15:21
@GreyHak I also often encounter this problem, just now I reproduced this problem on the latest version: `DSP_Main-0.8.19.7863`  `BepInEx-5.4.11`  `DSP_Belt_Reverse_Direction-1.1.1`

So I created a new clean configuration on r2modman, and created a new map for testing
![new config](https://user-images.githubusercontent.com/7929014/129220144-9d89e224-ce69-455b-a48e-c1a739d6c5ea.png "new config")
![new map](https://user-images.githubusercontent.com/7929014/129220298-925a359e-67c8-4bcf-9cbe-afc2c4337a54.png "new map")

Then I unlocked the necessary tech and started testing, sorters disconnect after S/L
![after](https://user-images.githubusercontent.com/7929014/129222949-fce6e117-8abc-42ce-add3-7f5109ced529.gif)

**Comment by GreyHak** [comment] 2021-08-13 00:29
@muink Thank you for the video.  I've reproduced the issue.  It appears that outgoing connections stay working, but incoming connections get broken.  Reopening report.

**Comment by GreyHak** [comment] 2021-08-14 04:25
@cdcrothers and @muink This issue should be fixed in v1.1.2.  Thank you again for the report.

**Closed by GreyHak** 2021-08-14 04:25 UTC
Labels: bug
